spring:
  application:
    name: product=service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
  info :
    component : product service

---
spring:
  jpa :
    hibernate:
      ddl-auto : update
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate :
        default_schema: stock_management

  datasource:
    url : "jdbc:postgresql://localhost:5432/stock_management "
    username : postgres
    password : Paspas5202940




